// Build-time image optimizer.
// Reads raw screenshots from assets/raw (outside public/, so Vite never ships
// the originals) and emits width-capped AVIF + WebP + a JPEG fallback into
// public/images, plus a manifest of real output dimensions so the page can
// reserve the right box and avoid layout shift.
import sharp from 'sharp'
import { readdir, mkdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'

const SRC = 'assets/raw'
const OUT = 'public/images'
const MANIFEST = 'src/data/images.ts'
const WIDTHS = [640, 1280]

const kb = (b) => `${(b / 1024).toFixed(0)} KB`
const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

await mkdir(OUT, { recursive: true })

const files = (await readdir(SRC)).filter((f) => /\.(png|jpe?g)$/i.test(f))
if (!files.length) {
  console.log(`No source images in ${SRC}`)
  process.exit(0)
}

let before = 0
let after = 0
const manifest = {}

for (const file of files) {
  const src = path.join(SRC, file)
  const base = slug(path.parse(file).name)
  const original = (await stat(src)).size
  before += original

  const meta = await sharp(src).metadata()
  const srcWidth = meta.width ?? WIDTHS.at(-1)
  const widths = [...new Set(WIDTHS.map((w) => Math.min(w, srcWidth)))].sort((a, b) => a - b)
  const largest = Math.max(...widths)

  let produced = 0
  for (const w of widths) {
    const suffix = w === largest ? '' : `-${w}`
    const pipeline = sharp(src).resize({ width: w, withoutEnlargement: true })

    const [avif, webp, jpg] = await Promise.all([
      pipeline.clone().avif({ quality: 55, effort: 6 }).toFile(`${OUT}/${base}${suffix}.avif`),
      pipeline.clone().webp({ quality: 78 }).toFile(`${OUT}/${base}${suffix}.webp`),
      pipeline.clone().jpeg({ quality: 80, mozjpeg: true }).toFile(`${OUT}/${base}${suffix}.jpg`),
    ])
    produced += avif.size + webp.size + jpg.size

    if (w === largest) {
      manifest[base] = { width: avif.width, height: avif.height }
      after += avif.size
    }
  }

  console.log(
    `${file.padEnd(18)} ${kb(original).padStart(9)} -> ${kb(manifest[base] ? produced : 0).padStart(9)} on disk` +
      `  (${widths.join(', ')}px, ${manifest[base].width}x${manifest[base].height})`,
  )
}

const body = `// Generated by scripts/optimize-images.mjs — do not edit by hand.
// Real output dimensions, used to reserve the correct box and avoid layout shift.
export const imageSizes: Record<string, { width: number; height: number }> = ${JSON.stringify(manifest, null, 2)}
`
await writeFile(MANIFEST, body)

console.log(
  `\nPrimary payload: ${kb(before)} -> ${kb(after)}  (${(100 - (after / before) * 100).toFixed(1)}% smaller)`,
)
console.log(`Wrote ${MANIFEST}`)
