// Generated by scripts/optimize-images.mjs — do not edit by hand.
// Real output dimensions, used to reserve the correct box and avoid layout shift.
export const imageSizes: Record<string, { width: number; height: number }> = {
  "aureon": {
    "width": 1280,
    "height": 578
  },
  "folio": {
    "width": 1280,
    "height": 800
  },
  "synsia": {
    "width": 1280,
    "height": 584
  },
  "vinevista": {
    "width": 1280,
    "height": 593
  }
}
