// Generated by scripts/optimize-images.mjs — do not edit by hand.
// Real output dimensions (so the page reserves the right box and does not
// shift on load) and the widths that actually exist on disk.
export type ImageMeta = { width: number; height: number; variants: number[] }

export const imageSizes: Record<string, ImageMeta> = {
  "aureon": {
    "width": 1280,
    "height": 578,
    "variants": [
      640,
      1280
    ]
  },
  "folio": {
    "width": 1280,
    "height": 800,
    "variants": [
      640,
      1280
    ]
  },
  "portrait": {
    "width": 878,
    "height": 938,
    "variants": [
      640,
      878
    ]
  },
  "synsia": {
    "width": 1280,
    "height": 584,
    "variants": [
      640,
      1280
    ]
  },
  "vinevista": {
    "width": 1280,
    "height": 593,
    "variants": [
      640,
      1280
    ]
  }
}
